### ISSUE TITLE
Deploying website

### ISSUE THREAD

**Issue by SvenNekula** [SvenNekula/newproject#1]
Hey @maxheld83,

last Semester we deployed our website, so they were hosted on GitHub-servers and could be found by typing the URL in the browser. 
Kinda forgot how we did that. Also forgot how we got the badge shown in the picture to display...
Could you help me out / link me a tutorial? 
Thanks in advance!

![GitHub_pages_deploybadge](https://user-images.githubusercontent.com/56732386/81409500-847d6900-913f-11ea-911d-f4f845229c01.jpg)

**Comment by maxheld83** [comment]
you can set up GitHub Actions by just commiting an appropriate `.github/workflows/filename.yaml` to your repository.
The yaml syntax therein is a bit finnicky, so it's best to just copy an existing one.

The one from your last project should still work:

```
name: Render and Deploy RMarkdown Website
'on': push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - run: |-
          Rscript -e "deploy_path <- rmarkdown::render_site(encoding = 'UTF-8')"
          Rscript -e "Sys.setenv(DEPLOY_PATH = '_site/')"
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: maxheld83/ghpages@v0.2.0
        env:
          BUILD_DIR: _site/
          GH_PAT: ${{ secrets.GH_PAT }}
    container: rocker/verse:latest
```

You can find out more about GitHub Actions here:

- https://github.com/r-lib/actions
- https://help.github.com/en/actions
